[package]
name = "advent2021"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "file-reader",
    "cli",
    "challenges",
]

[dependencies]

[[bin]]
name = "advent2021"
path = "main.rs"
